name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Run tests
      run: |
        python -m unittest discover -s . -p '*_test.py'
