name: Coffee System

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Run tests
      run: |
        python -m unittest test_Coffee.py

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build application
      run: |
        pyinstaller Coffee.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coffee-app
        path: dist
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: coffee-app
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: coffee-app
