# Nombre del workflow
name: Python application

# Activadores del workflow
on: [push]

# Trabajos que se ejecutar치n
jobs:

  build:

    # Sistema operativo en el que se ejecutar치 el trabajo
    runs-on: macos-latest

    steps:
    # Paso para hacer checkout del c칩digo fuente
    - uses: actions/checkout@v3
    
    # Paso para configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Versi칩n de Python a utilizar
        
    # Paso para ejecutar pruebas unitarias
    - name: Run tests
      run: |
        python -m unittest discover -s tests/ -p 'test_*.py' -v
        
    # Paso para construir el ejecutable
    - name: Build application
      run: |
        pyinstaller Coffee.py
        
    # Paso para empaquetar artefactos
    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coffee-app
        path: dist/Coffee
