name: Coffee System

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Run tests
      run: |
        python -m unittest discover -s . -p 'test_*.py' -v
        
  build:
    needs: test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller
        
    - name: Build application
      run: |
        pyinstaller Coffee.py
        
    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coffee-app
        path: dist/Coffee
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: coffee-app
        
    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        scp -r coffee-app $SERVER_USER@$SERVER_IP:/path/to/deploy/directory
